/**********************************************************************************
* @author       JVN - josep@clappsolutions.com - www.clappsolutions.com
* @date         19 June 2015
* @description  Controller class for MeetupSearch page.
*               Best practice:
*                   - Controller class must have the same name of the VF page.
* @Revision     
**********************************************************************************/
public with sharing class SDG_CtrlMeetupSearch {

	//-- CONSTRUCTOR
	/**
	 * Default constructor.
	 */
    public SDG_CtrlMeetupSearch() {
        
    }
}